apiVersion: v1
kind: Service
metadata:
  name: {{ include "analytics-service.fullname" . }}
  labels:
    app.kubernetes.io/name: {{ include "analytics-service.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/version: {{ .Chart.Version }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.port }}
      protocol: TCP
  selector:
    app.kubernetes.io/name: {{ include "analytics-service.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}