replicaCount: 1
image:
  repository: krobus00/analytics-service
  tag: v1.0.0
  pullPolicy: IfNotPresent
service:
  type: ClusterIP
  port: 5701
ingress:
  enabled: true
  annotations:
    traefik.ingress.kubernetes.io/router.entrypoints: websecure
    traefik.ingress.kubernetes.io/router.tls: "true"
  ingressClassName: traefik
  host: data.krobot.my.id
  path: '/'
autoscaling:
  enabled: true
  minReplicas: 1
  maxReplicas: 5
  targetMemoryUtilizationPercentage: 50
  # targetCPUUtilizationPercentage: 50

resources:
  limits:
    cpu: 1
    memory: 500Mi
  requests:
    cpu: 50m
    memory: 10Mi

configmap:
  enable: true
  values: |
  env: "value"