apiVersion: batch/v1
kind: Job
metadata:
  name: {{ include "analytics-service.fullname" . }}-migration
  labels:
    app.kubernetes.io/name: {{ include "analytics-service.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/version: {{ .Chart.Version }}
spec:
  ttlSecondsAfterFinished: 1
  template:
    metadata:
      labels:
        app.kubernetes.io/name: {{ include "analytics-service.name" . }}
        app.kubernetes.io/instance: {{ .Release.Name }}
    spec:
      restartPolicy: "OnFailure"
      containers:
        - name: {{ .Chart.Name }}-migration
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          command: ["/app/bin/analytics-service", "migration", "--action", "up"]
          volumeMounts:
            - name: {{ include "analytics-service.fullname" . }}
              mountPath: /app/config.yml
              subPath: config.yml
              readOnly: true
      volumes:
        - name: {{ include "analytics-service.fullname" . }}
          configMap:
            name: {{ include "analytics-service.fullname" . }}