{{ if .Values.configmap.enable }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "analytics-service.fullname" . }}
data:
  config.yml: |
{{ .Values.configmap.values | indent 4 }}

{{ end }}